### PR TITLE
Support User Defined Scalars

### PR DESCRIPTION
**Pull request by srikrsna**
Hi,

Thank you for this library, I particularly like Thunder's style and performance over other implementations, not to mention its name ⚡️.

I've tried to add a function which adds support for user defined types. This will help support types like ID. I can also add an example for this in a separate PR, if this gets accepted along with some tests.

If this is part of your roadmap please review the PR or else I'll maintain a fork.

This is related to #163 and #162.

Thank You.

### CODE REVIEW

**Comment by berfarah** [comment]
Hello @srikrsna, thanks for the contribution! We should have true support for custom scalars rolling out very, very soon! You can see my work here: https://github.com/samsarahq/thunder/tree/bf/types-2.0

I'm just working on some performance optimizations before merging.

**Comment by srikrsna** [comment]
@berfarah Thats great to hear. I'll definitely look into it. I'll abandon this PR. 
It would be nice to have a milestone/project roadmap to track features. I am more than happy to help in any way I can.

**Comment by srikrsna** [comment]
@berfarah I don't see any difference between master and your branch.

**Comment by berfarah** [comment]
@srikrsna might be better to diff between `v0.1.0` and my branch :)

**Comment by srikrsna** [comment]
@berfarah Any update on this?

**Comment by berfarah** [comment]
@srikrsna We have started on this but it likely won't be done any time soon (on the graphql side)

**Comment by srikrsna** [comment]
@berfarah Thank you for letting me know. Its great to know this is still on the roadmap. If you guys need anything I'd more than happy to help out.

**Comment by mmmveggies** [comment]
@berfarah is the progress for this still on https://github.com/samsarahq/thunder/tree/bf/types-2.0 ?

**Comment by pjvds** [comment]
@berfarah what's the status after 2 years? Need any help?

**Pull request closed without merging**
