### PR TITLE
sqlgen: introduce TypeConverter, support proto fields

### PR DESCRIPTION
**Pull request by jellevandenhooff**

### CODE REVIEW

**Comment by berfarah** [comment]
Nice! I see you added a check to see if the protobuf interface is implemented. I wonder if we could do something similar for JSON and SQL interfaces?
### JSON
https://golang.org/pkg/encoding/json/#Marshaler
https://golang.org/pkg/encoding/json/#Unmarshaler

### JSON fallback
https://golang.org/pkg/encoding/#TextMarshaler
https://golang.org/pkg/encoding/#TextUnmarshaler

### SQL
https://golang.org/pkg/database/sql/#Scanner
https://golang.org/pkg/database/sql/driver/#Valuer

**Comment by berfarah** [comment]
This breaks `livesql/binlog` - I'm investigating alternatives here.

**Comment by stephen** [comment]
could you roughly describe how?

**Comment by berfarah** [comment]
Yep! We're getting rid of scannables here, but `livesql/binlog.go` depends on them. I don't think this abstraction quite works. I think what we need is a type that can give us a SQL type and convert to/from it.

**Comment by berfarah** [comment]
Closing as this has been addressed in https://github.com/samsarahq/thunder/pull/142

**Pull request closed without merging**
